### ISSUE TITLE
Acquisition of billion sized image-text-pairs dataset

### ISSUE THREAD

**Issue by rvencu** [LAION-AI/project-menu#1]
Continue the workflow to transform Common Crawl data into a billion sized image-text-pairs dataset. Currently at about 1.2 billion in size.
Basic workflow steps are:
1. parsing the common crawl WAT files and retain candidates URL-text pairs
2. download the images at URLs and filter unwanted items, also resize to 224x224 with center-crop the remaining ones
3. send batches of images and metadata to CLIP inference to calculate similarity scores, then keep only pairs with score > 0.3

**Comment by rom1504** [comment]
done and released
