### ISSUE TITLE
Build a good safety model

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/project-menu#2]
More information at https://github.com/christophschuhmann/Finetune-EfficientNet-V2_for_NSFW_Detection/issues

**Comment by rom1504** [comment]
https://github.com/LAION-AI/LAION-SAFETY

**Comment by rom1504** [comment]
the current tasks that would be most useful are :
1. Assembling a dataset sampled from laion 400M of nsfw and non nsfw data as metadata (keeping the url the text and the image)
2. Building a simple clip embedding to nsfw vs non nsfw classifier
3. Building an inference job from embedding to prediction: this will run at more than 100k sample/s on CPU

This path will get us a classifier which we can afford to run

**Comment by sayakpaul** [comment]
@rom1504 I can work on the first one following our discussions over the server.

**Comment by rom1504** [comment]
done and released
