### ISSUE TITLE
expand to multilingual captions

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/project-menu#8]
Multilingual clip can be used as a filter
https://huggingface.co/sentence-transformers/clip-ViT-B-32-multilingual-v1

try it at https://colab.research.google.com/drive/1kOKsf-X0nS2_ael7scPa9raf0pBmxUgW#scrollTo=ScN8GQwN3xXq

First experimentations show that clip is still ok at  latin languages (french, portuguese, spanish, french)
very bad at non latin, especially so for non european
mclip keeps the same ordering of performances, but it still ok for the most difficult languages
so maybe we want to decrease 0.3 to like 0.26 for mclip

**Comment by rom1504** [comment]
interesting things to do:
* [ ] evaluate on more samples (for example take a bunch of samples from laion, translate the captions and run mclip and clip to get the matches)
* [ ] integrate mclip in the worker script

**Comment by rom1504** [comment]
probably https://github.com/ARKseal/crawlingathome-worker/blob/master/clip_filter.py

**Comment by rvencu** [comment]
please use this, it is the latest version in use https://github.com/rvencu/crawlingathome-gpu-hcloud/blob/main/clip_filter.py

**Comment by rom1504** [comment]
this is ongoing, already 700M samples extracted

**Comment by rom1504** [comment]
done and released
